#!/bin/bash

# 获取当前脚本所在目录
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")

# 加载gvm
[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"
if [ -z "$1" ];then
    code 
elif [ -f "$1" ];then
    code "$1"
elif [ -d "$1" ];then
    if [ -f "$1/go.mod" ];then
        go_version=$(awk '/^go / {print $2}' "$1/go.mod")
        echo "打开的是一个go项目，go版本为${go_version}"
        gvm use go${go_version}
        echo "设置CONSUL_HTTP_HOST"
        devbox_ip=$(cat ${SCRIPT_DIR}/env.json | jq -r '.devbox_ip')
        export CONSUL_HTTP_HOST=${devbox_ip}
        code "$1"
    else
        code "$1"
    fi
fi


##############################################################
#   添加软链到/usr/local/bin                                   #
#   sudo ln -s /Users/xxx/xxx/zcode /usr/local/bin/zcode     #
##############################################################


# need install gvm and jq